// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Portal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SD2;

public abstract class Callback_Portal_getStreamList extends Ice.TwowayCallback
{
    public abstract void response(StreamInfo[] __ret);

    public final void __completed(Ice.AsyncResult __result)
    {
        PortalPrx __proxy = (PortalPrx)__result.getProxy();
        StreamInfo[] __ret = null;
        try
        {
            __ret = __proxy.end_getStreamList(__result);
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(__ret);
    }
}
