// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Portal.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package SD2;

public interface PortalPrx extends Ice.ObjectPrx
{
    public void registerStreamer(StreamInfo s);

    public void registerStreamer(StreamInfo s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerStreamer(StreamInfo s);

    public Ice.AsyncResult begin_registerStreamer(StreamInfo s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_registerStreamer(StreamInfo s, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerStreamer(StreamInfo s, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_registerStreamer(StreamInfo s, Callback_Portal_registerStreamer __cb);

    public Ice.AsyncResult begin_registerStreamer(StreamInfo s, java.util.Map<String, String> __ctx, Callback_Portal_registerStreamer __cb);

    public void end_registerStreamer(Ice.AsyncResult __result);

    public void closeStreamer(StreamInfo s);

    public void closeStreamer(StreamInfo s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_closeStreamer(StreamInfo s);

    public Ice.AsyncResult begin_closeStreamer(StreamInfo s, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_closeStreamer(StreamInfo s, Ice.Callback __cb);

    public Ice.AsyncResult begin_closeStreamer(StreamInfo s, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_closeStreamer(StreamInfo s, Callback_Portal_closeStreamer __cb);

    public Ice.AsyncResult begin_closeStreamer(StreamInfo s, java.util.Map<String, String> __ctx, Callback_Portal_closeStreamer __cb);

    public void end_closeStreamer(Ice.AsyncResult __result);

    public StreamInfo[] getStreamList();

    public StreamInfo[] getStreamList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStreamList();

    public Ice.AsyncResult begin_getStreamList(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_getStreamList(Ice.Callback __cb);

    public Ice.AsyncResult begin_getStreamList(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_getStreamList(Callback_Portal_getStreamList __cb);

    public Ice.AsyncResult begin_getStreamList(java.util.Map<String, String> __ctx, Callback_Portal_getStreamList __cb);

    public StreamInfo[] end_getStreamList(Ice.AsyncResult __result);
}
